sonar.projectKey=pawlo21_bis_policy_rate_monitor
sonar.organization=pawlo21


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=bis_policy_rate_monitor
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
